name-template: 'v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'
exclude-labels:
  - 'promotion'
categories:
  - title: '⭐️ 新機能'
    labels:
      - 'feature'
  - title: '🔥 改善'
    labels:
      - 'kaizen'
  - title: '🦊 お客様に関係しない変更'
    labels:
      - 'chore'
  - title: '🪲 不具合修正'
    labels:
      - 'fix'
      - 'hotfix'
  - title: その他の修正
    labels:
      - "*"
autolabeler:
  - label: 'feature'
    branch:
      - '/^feature.+/'
  - label: 'kaizen'
    branch:
      - '/^kaizen.+/'
  - label: 'chore'
    branch:
      - '/^chore.+/'
  - label: 'fix'
    branch:
      - '/^fix\/.+/'
  - label: 'hotfix'
    branch:
      - '/^hotfix\/.+/'
  - label: 'promotion'
    branch:
      - '/^(develop|staging)$/i'
category-template: '### $TITLE'
change-template: '- #$NUMBER $TITLE by @$AUTHOR : $URL'
template: |
  ## 変更点一覧 
  $CHANGES