name-template: 'v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'
exclude-labels:
  - 'promotion'
categories:
  - title: ':rocket: 機能追加'
    labels:
      - 'feature'
  - title: ':bug: バグ修正'
    labels:
      - 'fix'
      - 'hotfix'
autolabeler:
  - label: 'feature'
    branch:
      - '/^feature.+/'
  - label: 'fix'
    branch:
      - '/^fix\/.+/'
  - label: 'hotfix'
    branch:
      - '/^hotfix\/.+/'
  - label: 'promotion'
    branch:
#      - '/^staging$/'
      - '/^develop$/'
category-template: '### $TITLE'
change-template: '- #$NUMBER $TITLE by @$AUTHOR : $URL'
template: |
  ## 変更点一覧 
  $CHANGES
  
  ## Contributors
  $CONTRIBUTORS

