name-template: 'v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'
exclude-labels:
  - 'promotion'
categories:
  - title: ':rocket: 機能追加'
    labels:
      - 'feature'
  - title: ':bug: バグ修正'
    labels:
      - 'fix'
      - 'hotfix'
  - title: ':beer: メンテナンス'
    labels:
      - 'chore'
autolabeler:
  - label: 'feature'
    branch:
      - '/feature.+/'
  - label: 'fix'
    branch:
      - '/fix\/.+/'
  - label: 'hotfix'
    branch:
      - '/hotfix\/.+/'
  - label: 'chore'
    branch:
      - '/chore\/.+/'
change-template: '- #$NUMBER $TITLE (@$AUTHOR)'
template: |
  ## Changes
  $CHANGES

