name: Release Drafter

on:
  pull_request:
    types: [opened, reopened, synchronize, closed]

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5.18.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
